### PR TITLE
Kh/dp/take user offline

### PR DESCRIPTION
**Pull request by kheppenstall**
-Add status to user column
-Scope projects to only online projects in index
-Add admin functionality to toggle users between online and offline
-No one can visit the view or new pledge page for an offline project

Had to change some tests to give projects users.

@drod1000 @case-eee @Robbie-Smith @jdconrad89 Ready for review. Needs one reviewer.

### CODE REVIEW

**Comment by Dpalazzari** [comment]
@drod1000 @jdconrad89 @Robbie-Smith This is ready for review.

**Comment by Dpalazzari** [comment]
@Robbie-Smith @drod1000 @jdconrad89 Hey guys can we get this reviewed and merged?

**Comment by Robbie-Smith** [comment]
@Dpalazzari Taking a look now.

**Comment by Robbie-Smith** [comment]
@Dpalazzari @kheppenstall looks good.

**Pull request merged**
