### PR TITLE
Dr#42 api projects

### PR DESCRIPTION
**Pull request by drod1000**

### CODE REVIEW

**Comment by drod1000** [comment]
@Robbie-Smith @jdconrad89 @Dpalazzari 
worked on this with @kheppenstall , needs two more reviewers

**Comment by Robbie-Smith** [comment]
@drod1000 I'm grabbing lunch. I'll be back at 1.

**Comment by drod1000** [comment]
@Robbie-Smith @jdconrad89 @Dpalazzari 
We skipped visitor can view project show page test. We're going to work on that one on a separate branch now.

**Comment by Robbie-Smith** [comment]
Looks good to me!

**Comment by Dpalazzari** [comment]
You can merge it @Robbie-Smith

**Comment by jdconrad89** [comment]
@drod1000  Looks good to me! Let's merge it!

image

**Pull request merged**
